apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-nodejs
  template:
    metadata:
      labels:
        app: dummy-nodejs
    spec:
      containers:
      - name: nodejs
        image: node:16-alpine
        command: ["node", "-e", "require('http').createServer((req, res) => res.end('Hello from Node.js')).listen(5000)"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: dummy-nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
